name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install apt-get packages
      run: |
        sudo apt-get install build-essential curl wget git vim libboost-all-dev
    
    - name: Install deno and ssvmup
      run: |
        curl -fsSL https://deno.land/x/install/install.sh | sh
        echo '::add-path::$HOME/.deno/bin'
        curl https://raw.githubusercontent.com/second-state/ssvmup/master/installer/init.sh -sSf | sh
    
    - name: Build
      run: ssvmup build --target deno
      
    - name: Test
      run: |
        deno deno/test.js
        ssvmup clean
